import type { Ward, Patient, InventoryItem, Transaction } from './types';
// seed data

export const WARDS: Ward[] = [
  { id: 'w1', name: 'Ward 4A — General Medicine', sweepStatus: 'dispensed', activePatients: 18 },
  { id: 'w2', name: 'Ward 5B — Cardiology', sweepStatus: 'swept', activePatients: 12 },
  { id: 'w3', name: 'Ward 6C — Orthopaedics', sweepStatus: 'pending', activePatients: 9 },
  { id: 'w4', name: 'Ward 2D — Oncology', sweepStatus: 'pending', activePatients: 14 },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p1',
    mrn: 'MRN-004821',
    name: 'Margaret Osei',
    dateOfBirth: '1968-03-14',
    gender: 'Female',
    phone: '+233 24 456 7890',
    ward: 'Ward 4A',
    bed: 'Bed 04',
    admissionDate: '2026-07-29',
    diagnosis: 'Type 2 Diabetes Mellitus, Hypertension',
    allergies: 'Penicillin',
    prescriptions: [
      {
        id: 'rx1', drug: 'Amoxicillin 500mg', dose: '500mg', route: 'Oral',
        frequency: 'TDS', foodTiming: 'after-food', timeOfDay: ['morning', 'afternoon', 'night'],
        startDate: '2026-07-29', durationDays: 7, currentDay: 7, status: 'active',
        notes: 'Complete full course even if symptoms improve.',
        prescribedBy: 'Dr. B. Kwame', prescribedAt: '2026-07-29 08:15',
      },
      {
        id: 'rx2', drug: 'Metformin 500mg', dose: '500mg', route: 'Oral',
        frequency: 'BD', foodTiming: 'with-food', timeOfDay: ['morning', 'night'],
        startDate: '2026-07-29', durationDays: 14, currentDay: 7, status: 'active',
        notes: 'Monitor blood glucose. Hold if eGFR falls below 30.',
        prescribedBy: 'Dr. B. Kwame', prescribedAt: '2026-07-29 08:15',
      },
      {
        id: 'rx3', drug: 'Lisinopril 10mg', dose: '10mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'not-applicable', timeOfDay: ['morning'],
        startDate: '2026-07-29', durationDays: 14, currentDay: 7, status: 'active',
        notes: 'Check BP before each dose. Hold if systolic < 90 mmHg.',
        prescribedBy: 'Dr. B. Kwame', prescribedAt: '2026-07-29 08:15',
      },
    ],
  },
  {
    id: 'p2',
    mrn: 'MRN-003145',
    name: 'James Kofi Antwi',
    dateOfBirth: '1952-11-07',
    gender: 'Male',
    phone: '+233 20 345 6789',
    ward: 'Ward 4A',
    bed: 'Bed 07',
    admissionDate: '2026-08-01',
    diagnosis: 'Congestive Heart Failure (NYHA Class III)',
    allergies: 'None known',
    prescriptions: [
      {
        id: 'rx4', drug: 'Furosemide 40mg', dose: '40mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'not-applicable', timeOfDay: ['morning'],
        startDate: '2026-08-01', durationDays: 5, currentDay: 4, status: 'active',
        notes: 'Administer early morning. Monitor fluid balance and electrolytes daily.',
        prescribedBy: 'Dr. B. Kwame', prescribedAt: '2026-08-01 07:30',
      },
      {
        id: 'rx5', drug: 'Spironolactone 25mg', dose: '25mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'with-food', timeOfDay: ['morning'],
        startDate: '2026-08-01', durationDays: 5, currentDay: 4, status: 'active',
        notes: 'Monitor potassium levels closely.',
        prescribedBy: 'Dr. B. Kwame', prescribedAt: '2026-08-01 07:30',
      },
      {
        id: 'rx6', drug: 'Digoxin 0.25mg', dose: '0.25mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'before-food', timeOfDay: ['morning'],
        startDate: '2026-07-31', durationDays: 3, currentDay: 5, status: 'stopped',
        stopReason: 'Toxicity suspected — digoxin level 3.1 ng/mL',
        prescribedBy: 'Dr. B. Kwame', prescribedAt: '2026-07-31 09:00',
      },
    ],
  },
  {
    id: 'p3',
    mrn: 'MRN-007302',
    name: 'Abena Frimpong',
    dateOfBirth: '1975-06-22',
    gender: 'Female',
    phone: '+233 27 891 2345',
    ward: 'Ward 5B',
    bed: 'Bed 12',
    admissionDate: '2026-07-31',
    diagnosis: 'Acute Myocardial Infarction (NSTEMI)',
    allergies: 'Sulfonamides',
    prescriptions: [
      {
        id: 'rx7', drug: 'Atorvastatin 40mg', dose: '40mg', route: 'Oral',
        frequency: 'ON', foodTiming: 'not-applicable', timeOfDay: ['night'],
        startDate: '2026-07-31', durationDays: 14, currentDay: 5, status: 'active',
        prescribedBy: 'Dr. E. Asare', prescribedAt: '2026-07-31 10:00',
      },
      {
        id: 'rx8', drug: 'Aspirin 75mg', dose: '75mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'after-food', timeOfDay: ['morning'],
        startDate: '2026-07-31', durationDays: 14, currentDay: 5, status: 'active',
        notes: 'Do not crush. Take with a full glass of water.',
        prescribedBy: 'Dr. E. Asare', prescribedAt: '2026-07-31 10:00',
      },
      {
        id: 'rx9', drug: 'Clopidogrel 75mg', dose: '75mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'after-food', timeOfDay: ['morning'],
        startDate: '2026-07-31', durationDays: 14, currentDay: 5, status: 'active',
        prescribedBy: 'Dr. E. Asare', prescribedAt: '2026-07-31 10:00',
      },
      {
        id: 'rx10', drug: 'Bisoprolol 5mg', dose: '5mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'not-applicable', timeOfDay: ['morning'],
        startDate: '2026-07-31', durationDays: 14, currentDay: 5, status: 'active',
        notes: 'Check resting HR before dose. Hold if HR < 50 bpm.',
        prescribedBy: 'Dr. E. Asare', prescribedAt: '2026-07-31 10:00',
      },
    ],
  },
  {
    id: 'p4',
    mrn: 'MRN-009881',
    name: 'Kwame Asante',
    dateOfBirth: '1989-09-03',
    gender: 'Male',
    phone: '+233 55 234 5678',
    ward: 'Ward 6C',
    bed: 'Bed 03',
    admissionDate: '2026-08-02',
    diagnosis: 'Right femur fracture, post-ORIF',
    allergies: 'None known',
    prescriptions: [
      {
        id: 'rx11', drug: 'Tramadol 50mg', dose: '50mg', route: 'Oral',
        frequency: 'QDS', foodTiming: 'after-food', timeOfDay: ['morning', 'afternoon', 'evening', 'night'],
        startDate: '2026-08-02', durationDays: 5, currentDay: 3, status: 'active',
        notes: 'Max 400mg/day. Avoid alcohol. May cause drowsiness.',
        prescribedBy: 'Dr. S. Acheampong', prescribedAt: '2026-08-02 14:00',
      },
      {
        id: 'rx12', drug: 'Ibuprofen 400mg', dose: '400mg', route: 'Oral',
        frequency: 'TDS', foodTiming: 'after-food', timeOfDay: ['morning', 'afternoon', 'night'],
        startDate: '2026-08-02', durationDays: 5, currentDay: 3, status: 'active',
        notes: 'Take with food or milk to reduce GI upset.',
        prescribedBy: 'Dr. S. Acheampong', prescribedAt: '2026-08-02 14:00',
      },
    ],
  },
  {
    id: 'p5',
    mrn: 'MRN-002017',
    name: 'Esi Mensah',
    dateOfBirth: '1961-01-28',
    gender: 'Female',
    phone: '+233 24 678 9012',
    ward: 'Ward 2D',
    bed: 'Bed 09',
    admissionDate: '2026-07-20',
    diagnosis: 'Breast carcinoma, cycle 3 chemotherapy',
    allergies: 'Codeine',
    prescriptions: [
      {
        id: 'rx13', drug: 'Ondansetron 8mg', dose: '8mg', route: 'Oral',
        frequency: 'TDS', foodTiming: 'before-food', timeOfDay: ['morning', 'afternoon', 'night'],
        startDate: '2026-07-20', durationDays: 21, currentDay: 16, status: 'active',
        notes: 'Give 30 min before meals to prevent chemotherapy-induced nausea.',
        prescribedBy: 'Dr. A. Boateng', prescribedAt: '2026-07-20 09:00',
      },
      {
        id: 'rx14', drug: 'Metoclopramide 10mg', dose: '10mg', route: 'Oral',
        frequency: 'TDS', foodTiming: 'before-food', timeOfDay: ['morning', 'afternoon', 'night'],
        startDate: '2026-07-20', durationDays: 21, currentDay: 16, status: 'active',
        prescribedBy: 'Dr. A. Boateng', prescribedAt: '2026-07-20 09:00',
      },
      {
        id: 'rx15', drug: 'Dexamethasone 4mg', dose: '4mg', route: 'Oral',
        frequency: 'OD', foodTiming: 'after-food', timeOfDay: ['morning'],
        startDate: '2026-07-20', durationDays: 21, currentDay: 16, status: 'active',
        notes: 'Taper dose in final 3 days. Do not stop abruptly.',
        prescribedBy: 'Dr. A. Boateng', prescribedAt: '2026-07-20 09:00',
      },
    ],
  },
];

export const INVENTORY: InventoryItem[] = [
  { id: 'i1', drug: 'Amoxicillin 500mg', category: 'Antibiotics', unit: 'Capsule', currentStock: 340, reorderLevel: 100, status: 'ok' },
  { id: 'i2', drug: 'Furosemide 40mg', category: 'Diuretics', unit: 'Tablet', currentStock: 52, reorderLevel: 100, status: 'low' },
  { id: 'i3', drug: 'Metformin 500mg', category: 'Antidiabetics', unit: 'Tablet', currentStock: 210, reorderLevel: 100, status: 'ok' },
  { id: 'i4', drug: 'Lisinopril 10mg', category: 'Antihypertensives', unit: 'Tablet', currentStock: 18, reorderLevel: 50, status: 'critical' },
  { id: 'i5', drug: 'Tramadol 50mg', category: 'Analgesics', unit: 'Capsule', currentStock: 95, reorderLevel: 100, status: 'low' },
  { id: 'i6', drug: 'Atorvastatin 40mg', category: 'Lipid-lowering', unit: 'Tablet', currentStock: 288, reorderLevel: 80, status: 'ok' },
  { id: 'i7', drug: 'Aspirin 75mg', category: 'Antiplatelets', unit: 'Tablet', currentStock: 412, reorderLevel: 100, status: 'ok' },
  { id: 'i8', drug: 'Clopidogrel 75mg', category: 'Antiplatelets', unit: 'Tablet', currentStock: 7, reorderLevel: 50, status: 'critical' },
  { id: 'i9', drug: 'Bisoprolol 5mg', category: 'Beta-blockers', unit: 'Tablet', currentStock: 156, reorderLevel: 80, status: 'ok' },
  { id: 'i10', drug: 'Ondansetron 8mg', category: 'Antiemetics', unit: 'Tablet', currentStock: 64, reorderLevel: 80, status: 'low' },
  { id: 'i11', drug: 'Dexamethasone 4mg', category: 'Corticosteroids', unit: 'Tablet', currentStock: 89, reorderLevel: 60, status: 'ok' },
  { id: 'i12', drug: 'Spironolactone 25mg', category: 'Diuretics', unit: 'Tablet', currentStock: 3, reorderLevel: 50, status: 'critical' },
];

export const TRANSACTIONS: Transaction[] = [
  { id: 'TXN-20260805-0041', batchId: 'BT-0805-A', patient: 'Margaret Osei', ward: 'Ward 4A', drug: 'Amoxicillin 500mg', qty: 3, unitPrice: 0.85, total: 2.55, timestamp: '2026-08-05 07:14', status: 'billed' },
  { id: 'TXN-20260805-0042', batchId: 'BT-0805-A', patient: 'Margaret Osei', ward: 'Ward 4A', drug: 'Metformin 500mg', qty: 4, unitPrice: 0.42, total: 1.68, timestamp: '2026-08-05 07:14', status: 'billed' },
  { id: 'TXN-20260805-0043', batchId: 'BT-0805-A', patient: 'James Kofi Antwi', ward: 'Ward 4A', drug: 'Furosemide 40mg', qty: 2, unitPrice: 0.30, total: 0.60, timestamp: '2026-08-05 07:17', status: 'billed' },
  { id: 'TXN-20260805-0044', batchId: 'BT-0805-B', patient: 'Abena Frimpong', ward: 'Ward 5B', drug: 'Atorvastatin 40mg', qty: 5, unitPrice: 1.20, total: 6.00, timestamp: '2026-08-05 07:45', status: 'billed' },
  { id: 'TXN-20260805-0045', batchId: 'BT-0805-B', patient: 'Abena Frimpong', ward: 'Ward 5B', drug: 'Aspirin 75mg', qty: 5, unitPrice: 0.12, total: 0.60, timestamp: '2026-08-05 07:45', status: 'billed' },
  { id: 'TXN-20260805-0046', batchId: 'BT-0805-C', patient: 'Kwame Asante', ward: 'Ward 6C', drug: 'Tramadol 50mg', qty: 16, unitPrice: 0.65, total: 10.40, timestamp: '2026-08-05 08:02', status: 'pending' },
  { id: 'TXN-20260805-0047', batchId: 'BT-0805-D', patient: 'Esi Mensah', ward: 'Ward 2D', drug: 'Ondansetron 8mg', qty: 3, unitPrice: 2.10, total: 6.30, timestamp: '2026-08-05 08:30', status: 'pending' },
  { id: 'TXN-20260804-0038', batchId: 'BT-0804-A', patient: 'James Kofi Antwi', ward: 'Ward 4A', drug: 'Furosemide 40mg', qty: 2, unitPrice: 0.30, total: 0.60, timestamp: '2026-08-04 07:20', status: 'billed' },
];
